package com.example.pakforces.ui.theme

import androidx.compose.ui.graphics.Color

// ─────────────────────────────────────────────────────────────────────────────
// BRAND — Signature Pak Forces identity (deep navy + military gold)
// ─────────────────────────────────────────────────────────────────────────────
val BrandNavy = Color(0xFF0B1F3A)
val BrandNavyLight = Color(0xFF1B3A5F)
val BrandGold = Color(0xFFD4A85A)
val BrandGoldSoft = Color(0xFFE8C97E)
val BrandCream = Color(0xFFF7F4EE)
val BrandInk = Color(0xFF11151C)

// ─────────────────────────────────────────────────────────────────────────────
// ARMY — Olive / Khaki / Slate
// ─────────────────────────────────────────────────────────────────────────────
val ArmyPrimary = Color(0xFF4A5A2A)         // olive green
val ArmyOnPrimary = Color(0xFFF7F4EE)
val ArmyPrimaryContainer = Color(0xFFCBD49B)
val ArmyOnPrimaryContainer = Color(0xFF101700)
val ArmySecondary = Color(0xFFC9A45B)        // gold
val ArmyOnSecondary = Color(0xFF1B1400)
val ArmySecondaryContainer = Color(0xFFFAE6BB)
val ArmyOnSecondaryContainer = Color(0xFF2A1F00)
val ArmyTertiary = Color(0xFFB23A48)
val ArmyOnTertiary = Color(0xFFFFFFFF)
val ArmyBackground = Color(0xFFFBFAF4)
val ArmyOnBackground = Color(0xFF1B1C16)
val ArmySurface = Color(0xFFFFFBF0)
val ArmyOnSurface = Color(0xFF1B1C16)
val ArmySurfaceVariant = Color(0xFFE2E3D2)
val ArmyOnSurfaceVariant = Color(0xFF45472F)
val ArmyOutline = Color(0xFF767760)
val ArmyError = Color(0xFFBA1A1A)
val ArmyOnError = Color(0xFFFFFFFF)

// ARMY — Dark
val ArmyPrimaryDark = Color(0xFFB0C97A)
val ArmyOnPrimaryDark = Color(0xFF253000)
val ArmyPrimaryContainerDark = Color(0xFF374700)
val ArmyOnPrimaryContainerDark = Color(0xFFCBD49B)
val ArmySecondaryDark = Color(0xFFDDCA83)
val ArmyOnSecondaryDark = Color(0xFF3A2E00)
val ArmySecondaryContainerDark = Color(0xFF534600)
val ArmyOnSecondaryContainerDark = Color(0xFFFAE6BB)
val ArmyTertiaryDark = Color(0xFFFFB4B4)
val ArmyOnTertiaryDark = Color(0xFF68000F)
val ArmyBackgroundDark = Color(0xFF13150C)
val ArmyOnBackgroundDark = Color(0xFFE4E3D2)
val ArmySurfaceDark = Color(0xFF1A1D11)
val ArmyOnSurfaceDark = Color(0xFFE4E3D2)
val ArmySurfaceVariantDark = Color(0xFF45472F)
val ArmyOnSurfaceVariantDark = Color(0xFFC6C7B0)
val ArmyOutlineDark = Color(0xFF8F9079)

// ─────────────────────────────────────────────────────────────────────────────
// AIR FORCE — Sky / Steel / Cloud
// ─────────────────────────────────────────────────────────────────────────────
val AirForcePrimary = Color(0xFF1F4E79)
val AirForceOnPrimary = Color(0xFFFFFFFF)
val AirForcePrimaryContainer = Color(0xFFD0E3FF)
val AirForceOnPrimaryContainer = Color(0xFF001D34)
val AirForceSecondary = Color(0xFF52606D)
val AirForceOnSecondary = Color(0xFFFFFFFF)
val AirForceSecondaryContainer = Color(0xFFD7E4F1)
val AirForceOnSecondaryContainer = Color(0xFF0F1D26)
val AirForceTertiary = Color(0xFF6B5778)
val AirForceOnTertiary = Color(0xFFFFFFFF)
val AirForceBackground = Color(0xFFFCFCFF)
val AirForceOnBackground = Color(0xFF1A1C1E)
val AirForceSurface = Color(0xFFFCFCFF)
val AirForceOnSurface = Color(0xFF1A1C1E)
val AirForceSurfaceVariant = Color(0xFFDEE3EB)
val AirForceOnSurfaceVariant = Color(0xFF42474E)
val AirForceOutline = Color(0xFF72777F)
val AirForceError = Color(0xFFBA1A1A)
val AirForceOnError = Color(0xFFFFFFFF)

val AirForcePrimaryDark = Color(0xFF9CCAFF)
val AirForceOnPrimaryDark = Color(0xFF003257)
val AirForcePrimaryContainerDark = Color(0xFF003E68)
val AirForceOnPrimaryContainerDark = Color(0xFFD0E3FF)
val AirForceSecondaryDark = Color(0xFFBBC8D6)
val AirForceOnSecondaryDark = Color(0xFF25323B)
val AirForceSecondaryContainerDark = Color(0xFF3B4853)
val AirForceOnSecondaryContainerDark = Color(0xFFD7E4F1)
val AirForceTertiaryDark = Color(0xFFD6BEE3)
val AirForceOnTertiaryDark = Color(0xFF382947)
val AirForceBackgroundDark = Color(0xFF1A1C1E)
val AirForceOnBackgroundDark = Color(0xFFE3E2E5)
val AirForceSurfaceDark = Color(0xFF1A1C1E)
val AirForceOnSurfaceDark = Color(0xFFE3E2E5)
val AirForceSurfaceVariantDark = Color(0xFF42474E)
val AirForceOnSurfaceVariantDark = Color(0xFFC2C7CF)
val AirForceOutlineDark = Color(0xFF8C9198)

// ─────────────────────────────────────────────────────────────────────────────
// NAVY — Deep Sea / Gold / Foam
// ─────────────────────────────────────────────────────────────────────────────
val NavyPrimary = Color(0xFF0F2E4C)
val NavyOnPrimary = Color(0xFFFFFFFF)
val NavyPrimaryContainer = Color(0xFFCDE2FF)
val NavyOnPrimaryContainer = Color(0xFF001D34)
val NavySecondary = Color(0xFFD4A85A)
val NavyOnSecondary = Color(0xFF1F1600)
val NavySecondaryContainer = Color(0xFFFFDF9A)
val NavyOnSecondaryContainer = Color(0xFF221A00)
val NavyTertiary = Color(0xFF62D0C5)
val NavyOnTertiary = Color(0xFF003734)
val NavyBackground = Color(0xFFF8F9FB)
val NavyOnBackground = Color(0xFF191C1F)
val NavySurface = Color(0xFFFFFFFF)
val NavyOnSurface = Color(0xFF191C1F)
val NavySurfaceVariant = Color(0xFFDDE3EA)
val NavyOnSurfaceVariant = Color(0xFF41474E)
val NavyOutline = Color(0xFF71787E)
val NavyError = Color(0xFFBA1A1A)
val NavyOnError = Color(0xFFFFFFFF)

val NavyPrimaryDark = Color(0xFF92CCF8)
val NavyOnPrimaryDark = Color(0xFF003354)
val NavyPrimaryContainerDark = Color(0xFF124A6E)
val NavyOnPrimaryContainerDark = Color(0xFFCDE2FF)
val NavySecondaryDark = Color(0xFFF2BD69)
val NavyOnSecondaryDark = Color(0xFF3A2900)
val NavySecondaryContainerDark = Color(0xFF533D00)
val NavyOnSecondaryContainerDark = Color(0xFFFFDF9A)
val NavyTertiaryDark = Color(0xFF44F0E3)
val NavyOnTertiaryDark = Color(0xFF00504B)
val NavyBackgroundDark = Color(0xFF0F1419)
val NavyOnBackgroundDark = Color(0xFFE0E3E7)
val NavySurfaceDark = Color(0xFF181E26)
val NavyOnSurfaceDark = Color(0xFFE0E3E7)
val NavySurfaceVariantDark = Color(0xFF41474E)
val NavyOnSurfaceVariantDark = Color(0xFFC1C7CE)
val NavyOutlineDark = Color(0xFF8B9197)

// ─────────────────────────────────────────────────────────────────────────────
// GENERIC — used for splash / onboarding / common screens
// ─────────────────────────────────────────────────────────────────────────────
val GenericPrimary = Color(0xFF1B3A5F)
val GenericOnPrimary = Color(0xFFFFFFFF)
val GenericPrimaryContainer = Color(0xFFD6E2F0)
val GenericOnPrimaryContainer = Color(0xFF001E36)
val GenericSecondary = Color(0xFFD4A85A)
val GenericOnSecondary = Color(0xFF1F1600)
val GenericBackground = Color(0xFFF7F4EE)
val GenericOnBackground = Color(0xFF1B1C16)
val GenericSurface = Color(0xFFFFFBF0)
val GenericOnSurface = Color(0xFF1B1C16)
val GenericSurfaceVariant = Color(0xFFE2E3D2)
val GenericOnSurfaceVariant = Color(0xFF45472F)
val GenericOutline = Color(0xFF767760)
val GenericError = Color(0xFFBA1A1A)
val GenericOnError = Color(0xFFFFFFFF)

val GenericPrimaryDark = Color(0xFF8FB4E0)
val GenericOnPrimaryDark = Color(0xFF002F5C)
val GenericPrimaryContainerDark = Color(0xFF1F3F65)
val GenericOnPrimaryContainerDark = Color(0xFFD6E2F0)
val GenericSecondaryDark = Color(0xFFE0C088)
val GenericOnSecondaryDark = Color(0xFF3A2900)
val GenericBackgroundDark = Color(0xFF0F1419)
val GenericOnBackgroundDark = Color(0xFFE0E3E7)
val GenericSurfaceDark = Color(0xFF181E26)
val GenericOnSurfaceDark = Color(0xFFE0E3E7)
val GenericSurfaceVariantDark = Color(0xFF41474E)
val GenericOnSurfaceVariantDark = Color(0xFFC1C7CE)
val GenericOutlineDark = Color(0xFF8B9197)

// Status / scoring colors
val ScoreExcellent = Color(0xFF2E7D32)
val ScoreGood = Color(0xFF388E3C)
val ScoreAverage = Color(0xFFF9A825)
val ScorePoor = Color(0xFFD32F2F)
