package com.example.pakforces.ui.navigation

/** All navigation routes in the app. */
object Routes {
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val HOME = "home"
    const val FORCE_PICKER = "force_picker"
    const val SUBJECT_PICKER = "subject_picker/{force}"
    const val TEST = "test/{force}/{category}/{mode}"
    const val RESULT = "result/{force}/{category}/{correct}/{total}/{timeSec}"
    const val PROGRESS = "progress"
    const val BOOKMARKS = "bookmarks"
    const val SETTINGS = "settings"
    const val DAILY_CHALLENGE = "daily_challenge"
    const val REVISION = "revision/{force}"
    const val SIMULATION = "simulation/{force}"
    const val PRACTICE = "practice/{force}"
    const val PRACTICE_TEST = "practice_test/{force}/{category}"
    const val LEARNING = "learning"
    const val ACHIEVEMENTS = "achievements"
    // v3
    const val ANALYTICS = "analytics"
    const val MOCK_EXAMS = "mock_exams/{force}"
    const val FLASHCARDS = "flashcards"
    const val MATH_FORMULAS = "math_formulas"
    const val ISLAMIC_REF = "islamic_ref"
    const val PAKISTAN_TIMELINE = "pakistan_timeline"
    const val MEDICAL = "medical"
    const val DOCUMENTS = "documents"
    const val DAY_IN_LIFE = "day_in_life"
    const val POMODORO = "pomodoro"
    const val MISSIONS = "missions"
    const val EXAM_COUNTDOWN = "exam_countdown"
    const val SMART_REVISION = "smart_revision"
    const val XP_SHOP = "xp_shop"
    const val CUSTOM_BUILDER = "custom_builder/{force}"
    const val TEST_PLANNER = "test_planner"

    fun subjectPicker(force: String) = "subject_picker/$force"
    fun test(force: String, category: String, mode: String) = "test/$force/$category/$mode"
    fun result(force: String, category: String, correct: Int, total: Int, timeSec: Int) =
        "result/$force/$category/$correct/$total/$timeSec"
    fun revision(force: String) = "revision/$force"
    fun simulation(force: String) = "simulation/$force"
    fun practice(force: String) = "practice/$force"
    fun practiceTest(force: String, category: String) = "practice_test/$force/$category"
    fun mockExams(force: String) = "mock_exams/$force"
    fun customBuilder(force: String) = "custom_builder/$force"
}
